
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Programlama Laboratuvari II Proje 4
 * @author Oguz Aktas
 */
public class FiltrelemeWindow extends javax.swing.JFrame {

    /**
     * Creates new form FiltrelemeWindow
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public FiltrelemeWindow() throws SQLException, ClassNotFoundException {
        initComponents();
        tablodaGoster();
    }
    
    public Connection getConnection() throws SQLException, ClassNotFoundException {
        Connection conn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/arac_alisveris", "root", "123456");
            return conn;
        } catch (SQLException ex) {
            Logger.getLogger(FiltrelemeWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Veritabanina baglanti saglanamadi");
        }
        return null;
    }
    
    public ArrayList<SQL> getList() throws SQLException, ClassNotFoundException {
        ArrayList<SQL> rowlist = new ArrayList<SQL>();
        Connection conn = getConnection();
        String query = "SELECT i.IlanID, i.Ilan_Adi, i.Ilan_Fiyat, i.Ilan_Km, i.Ilan_Tarih, a.Araba_Marka, a.Araba_Model, y.Yakit_Turu, v.Vites_Turu, r.Renk, s.Sehir FROM Tbl_Ilan i LEFT JOIN Tbl_Araba a ON i.Ilan_ArabaID = a.ArabaID LEFT JOIN Tbl_YakitTuru y ON a.Araba_YakitTuruID = y.YakitTuruID LEFT JOIN Tbl_VitesTuru v ON a.Araba_VitesTuruID = v.VitesTuruID LEFT JOIN Tbl_Renk r ON a.Araba_RenkID = r.RenkID LEFT JOIN Tbl_Sehir s ON i.Ilan_SehirID = s.SehirID ORDER BY i.IlanID;";
        Statement st;
        ResultSet rs;
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            SQL records;
            while(rs.next()) {
                records = new SQL(rs.getInt("IlanID"), rs.getString("Ilan_Adi"), Float.parseFloat(rs.getString("Ilan_Fiyat")), Float.parseFloat(rs.getString("Ilan_Km")), rs.getString("Ilan_Tarih"), rs.getString("Araba_Marka"), rs.getString("Araba_Model"), rs.getString("Yakit_Turu"), rs.getString("Vites_Turu"), rs.getString("Renk"), rs.getString("Sehir"));
                rowlist.add(records);
            }
            query = "SELECT * FROM Tbl_Sehir;";
            st = conn.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()) {
                combobox_sehir.addItem(rs.getString("Sehir"));
            }
            query = "SELECT * FROM Tbl_YakitTuru;";
            st = conn.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()) {
                combobox_yakit.addItem(rs.getString("Yakit_Turu"));
            }
            query = "SELECT * FROM Tbl_VitesTuru;";
            st = conn.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()) {
                combobox_vites.addItem(rs.getString("Vites_Turu"));
            }
            query = "SELECT * FROM Tbl_Renk;";
            st = conn.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()) {
                combobox_renk.addItem(rs.getString("Renk"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FiltrelemeWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rowlist;
    }
    
    public void tablodaGoster() throws SQLException, ClassNotFoundException {
        ArrayList<SQL> list = getList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] kayit = new Object[11];
        for (int i=0; i < list.size(); i++) {
            kayit[0] = list.get(i).getId();
            kayit[1] = list.get(i).getIlanadi();
            kayit[2] = list.get(i).getFiyat();
            kayit[3] = list.get(i).getKm();
            kayit[4] = list.get(i).getTarih();
            kayit[5] = list.get(i).getMarka();
            kayit[6] = list.get(i).getModel();
            kayit[7] = list.get(i).getYakitturu();
            kayit[8] = list.get(i).getVitesturu();
            kayit[9] = list.get(i).getRenk();
            kayit[10] = list.get(i).getSehir();
            model.addRow(kayit);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label_fiyat = new javax.swing.JLabel();
        label_sehir = new javax.swing.JLabel();
        label_yakit = new javax.swing.JLabel();
        label_vites = new javax.swing.JLabel();
        text_fiyatmin = new javax.swing.JTextField();
        text_fiyatmax = new javax.swing.JTextField();
        combobox_sehir = new javax.swing.JComboBox<>();
        combobox_yakit = new javax.swing.JComboBox<>();
        combobox_vites = new javax.swing.JComboBox<>();
        label_km = new javax.swing.JLabel();
        label_renk = new javax.swing.JLabel();
        label_tarih = new javax.swing.JLabel();
        combobox_renk = new javax.swing.JComboBox<>();
        combobox_tarih = new javax.swing.JComboBox<>();
        label_ilanadi = new javax.swing.JLabel();
        text_kmmin = new javax.swing.JTextField();
        text_kmmax = new javax.swing.JTextField();
        text_ilanadi = new javax.swing.JTextField();
        Btn_Sorgula = new javax.swing.JButton();
        Btn_Menu = new javax.swing.JButton();
        checkbox_sehir1 = new javax.swing.JCheckBox();
        checkbox_sehir2 = new javax.swing.JCheckBox();
        label_sirala1 = new javax.swing.JLabel();
        label_sirala2 = new javax.swing.JLabel();
        checkbox_fiyat1 = new javax.swing.JCheckBox();
        checkbox_fiyat2 = new javax.swing.JCheckBox();
        label_sirala3 = new javax.swing.JLabel();
        checkbox_marka1 = new javax.swing.JCheckBox();
        checkbox_marka2 = new javax.swing.JCheckBox();
        label_sirala4 = new javax.swing.JLabel();
        checkbox_model1 = new javax.swing.JCheckBox();
        checkbox_model2 = new javax.swing.JCheckBox();
        label_sirala5 = new javax.swing.JLabel();
        checkbox_ilanadi1 = new javax.swing.JCheckBox();
        checkbox_ilanadi2 = new javax.swing.JCheckBox();
        label_sirala6 = new javax.swing.JLabel();
        checkbox_tarih1 = new javax.swing.JCheckBox();
        checkbox_tarih2 = new javax.swing.JCheckBox();
        label_sirala7 = new javax.swing.JLabel();
        checkbox_id1 = new javax.swing.JCheckBox();
        checkbox_id2 = new javax.swing.JCheckBox();
        label_sirala8 = new javax.swing.JLabel();
        checkbox_km1 = new javax.swing.JCheckBox();
        checkbox_km2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setAutoscrolls(true);

        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ilan ID", "Ilan Adi", "Fiyat", "Km", "Tarih", "Marka", "Model", "Yakit Turu", "Vites Turu", "Renk", "Sehir"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        label_fiyat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_fiyat.setText("Fiyat araligini giriniz (min - max) : ");

        label_sehir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sehir.setText("Sehri seciniz : ");

        label_yakit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_yakit.setText("Yakit turunu seciniz : ");

        label_vites.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_vites.setText("Vites turunu seciniz : ");

        text_fiyatmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_fiyatmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_fiyatminActionPerformed(evt);
            }
        });

        text_fiyatmax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        combobox_sehir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox_sehir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tumu" }));

        combobox_yakit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox_yakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tumu" }));
        combobox_yakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_yakitActionPerformed(evt);
            }
        });

        combobox_vites.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox_vites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tumu" }));
        combobox_vites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_vitesActionPerformed(evt);
            }
        });

        label_km.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_km.setText("Km araligini giriniz (min - max) : ");

        label_renk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_renk.setText("Rengi seciniz : ");

        label_tarih.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_tarih.setText("Ilan tarihini seciniz : ");

        combobox_renk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox_renk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tumu" }));
        combobox_renk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_renkActionPerformed(evt);
            }
        });

        combobox_tarih.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox_tarih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tumu", "Son 24 Saat", "Son 1 Hafta", "Son 1 Ay" }));

        label_ilanadi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_ilanadi.setText("Ilan adinda aranacak kelimeyi giriniz : ");

        text_kmmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_kmmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_kmminActionPerformed(evt);
            }
        });

        text_kmmax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_kmmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_kmmaxActionPerformed(evt);
            }
        });

        text_ilanadi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_ilanadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ilanadiActionPerformed(evt);
            }
        });

        Btn_Sorgula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Sorgula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/sql.png"))); // NOI18N
        Btn_Sorgula.setText("Sorgula");
        Btn_Sorgula.setIconTextGap(10);
        Btn_Sorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SorgulaActionPerformed(evt);
            }
        });

        Btn_Menu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/home.png"))); // NOI18N
        Btn_Menu.setText("Ana Ekrana Git");
        Btn_Menu.setIconTextGap(10);
        Btn_Menu.setPreferredSize(new java.awt.Dimension(180, 51));
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        checkbox_sehir1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_sehir1.setText("Artan");
        checkbox_sehir1.setIconTextGap(6);
        checkbox_sehir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_sehir1ActionPerformed(evt);
            }
        });

        checkbox_sehir2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_sehir2.setText("Azalan");
        checkbox_sehir2.setIconTextGap(6);
        checkbox_sehir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_sehir2ActionPerformed(evt);
            }
        });

        label_sirala1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala1.setText("Sehre gore sirala : ");

        label_sirala2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala2.setText("Fiyata gore sirala : ");

        checkbox_fiyat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_fiyat1.setText("Artan");
        checkbox_fiyat1.setIconTextGap(6);
        checkbox_fiyat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_fiyat1ActionPerformed(evt);
            }
        });

        checkbox_fiyat2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_fiyat2.setText("Azalan");
        checkbox_fiyat2.setIconTextGap(6);
        checkbox_fiyat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_fiyat2ActionPerformed(evt);
            }
        });

        label_sirala3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala3.setText("Markaya gore sirala (A-Z) : ");

        checkbox_marka1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_marka1.setText("Artan");
        checkbox_marka1.setIconTextGap(6);
        checkbox_marka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_marka1ActionPerformed(evt);
            }
        });

        checkbox_marka2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_marka2.setText("Azalan");
        checkbox_marka2.setIconTextGap(6);
        checkbox_marka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_marka2ActionPerformed(evt);
            }
        });

        label_sirala4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala4.setText("Modele gore sirala (A-Z) : ");

        checkbox_model1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_model1.setText("Artan");
        checkbox_model1.setIconTextGap(6);
        checkbox_model1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_model1ActionPerformed(evt);
            }
        });

        checkbox_model2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_model2.setText("Azalan");
        checkbox_model2.setIconTextGap(6);
        checkbox_model2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_model2ActionPerformed(evt);
            }
        });

        label_sirala5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala5.setText("Ilan adina gore sirala (A-Z) : ");

        checkbox_ilanadi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_ilanadi1.setText("Artan");
        checkbox_ilanadi1.setIconTextGap(6);
        checkbox_ilanadi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_ilanadi1ActionPerformed(evt);
            }
        });

        checkbox_ilanadi2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_ilanadi2.setText("Azalan");
        checkbox_ilanadi2.setIconTextGap(6);
        checkbox_ilanadi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_ilanadi2ActionPerformed(evt);
            }
        });

        label_sirala6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala6.setText("Tarihe gore sirala : ");

        checkbox_tarih1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_tarih1.setText("Artan");
        checkbox_tarih1.setIconTextGap(6);
        checkbox_tarih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_tarih1ActionPerformed(evt);
            }
        });

        checkbox_tarih2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_tarih2.setText("Azalan");
        checkbox_tarih2.setIconTextGap(6);
        checkbox_tarih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_tarih2ActionPerformed(evt);
            }
        });

        label_sirala7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala7.setText("Ilan ID numarasina gore sirala : ");

        checkbox_id1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_id1.setSelected(true);
        checkbox_id1.setText("Artan");
        checkbox_id1.setIconTextGap(6);
        checkbox_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_id1ActionPerformed(evt);
            }
        });

        checkbox_id2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_id2.setText("Azalan");
        checkbox_id2.setIconTextGap(6);
        checkbox_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_id2ActionPerformed(evt);
            }
        });

        label_sirala8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sirala8.setText("Km'ye gore sirala : ");

        checkbox_km1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_km1.setText("Artan");
        checkbox_km1.setIconTextGap(6);
        checkbox_km1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_km1ActionPerformed(evt);
            }
        });

        checkbox_km2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox_km2.setText("Azalan");
        checkbox_km2.setIconTextGap(6);
        checkbox_km2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_km2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Sorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_sehir1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_sehir2)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_fiyat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_fiyatmin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_fiyatmax, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_marka1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_marka2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sehir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_sehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_yakit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_yakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_vites)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_vites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_ilanadi1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_ilanadi2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_id1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_id2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_km1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_km2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_tarih1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_tarih2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_ilanadi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_ilanadi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_tarih)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_renk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_renk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_km)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_kmmin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_kmmax, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_fiyat1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_fiyat2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_sirala4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_model1)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_model2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_km)
                            .addComponent(text_kmmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_kmmax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_sehir)
                            .addComponent(combobox_sehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fiyat)
                    .addComponent(label_renk)
                    .addComponent(combobox_renk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_fiyatmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_fiyatmax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_yakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_yakit)
                    .addComponent(label_tarih)
                    .addComponent(combobox_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_vites)
                    .addComponent(combobox_vites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ilanadi)
                    .addComponent(text_ilanadi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sirala1)
                    .addComponent(checkbox_sehir1)
                    .addComponent(checkbox_sehir2)
                    .addComponent(label_sirala2)
                    .addComponent(checkbox_fiyat1)
                    .addComponent(checkbox_fiyat2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sirala3)
                    .addComponent(checkbox_marka1)
                    .addComponent(checkbox_marka2)
                    .addComponent(label_sirala4)
                    .addComponent(checkbox_model1)
                    .addComponent(checkbox_model2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sirala5)
                    .addComponent(checkbox_ilanadi1)
                    .addComponent(checkbox_ilanadi2)
                    .addComponent(label_sirala6)
                    .addComponent(checkbox_tarih1)
                    .addComponent(checkbox_tarih2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sirala7)
                    .addComponent(checkbox_id1)
                    .addComponent(checkbox_id2)
                    .addComponent(label_sirala8)
                    .addComponent(checkbox_km1)
                    .addComponent(checkbox_km2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Sorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_renkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_renkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_renkActionPerformed

    private void text_fiyatminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_fiyatminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_fiyatminActionPerformed

    private void text_kmminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_kmminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_kmminActionPerformed

    private void text_ilanadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ilanadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ilanadiActionPerformed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        this.dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void Btn_SorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SorgulaActionPerformed
        String query = null;
        Connection conn = null;
        try {
            conn = getConnection();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FiltrelemeWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "SELECT i.IlanID, i.Ilan_Adi, i.Ilan_Fiyat, i.Ilan_Km, i.Ilan_Tarih, a.Araba_Marka, a.Araba_Model, y.Yakit_Turu, v.Vites_Turu, r.Renk, s.Sehir FROM Tbl_Ilan i LEFT JOIN Tbl_Araba a ON i.Ilan_ArabaID = a.ArabaID LEFT JOIN Tbl_YakitTuru y ON a.Araba_YakitTuruID = y.YakitTuruID LEFT JOIN Tbl_VitesTuru v ON a.Araba_VitesTuruID = v.VitesTuruID LEFT JOIN Tbl_Renk r ON a.Araba_RenkID = r.RenkID LEFT JOIN Tbl_Sehir s ON i.Ilan_SehirID = s.SehirID WHERE 1=1";
        if (combobox_sehir.getSelectedItem() != "Tumu") {
            query += " AND s.Sehir = '" + combobox_sehir.getSelectedItem() + "'";
        }
        if (combobox_yakit.getSelectedItem() != "Tumu") {
            query += " AND y.Yakit_Turu = '" + combobox_yakit.getSelectedItem() + "'";
        }
        if (combobox_vites.getSelectedItem() != "Tumu") {
            query += " AND v.Vites_Turu = '" + combobox_vites.getSelectedItem() + "'";
        }
        if (combobox_renk.getSelectedItem() != "Tumu") {
            query += " AND r.Renk = '" + combobox_renk.getSelectedItem() + "'";
        }
        if (combobox_tarih.getSelectedItem() != "Tumu") {
            if (combobox_tarih.getSelectedItem() == "Son 24 Saat") {
                query += " AND i.Ilan_Tarih > DATE_SUB(NOW(), INTERVAL 24 HOUR) AND i.Ilan_Tarih <= NOW()";
            } else if (combobox_tarih.getSelectedItem() == "Son 1 Hafta") {
                query += " AND i.Ilan_Tarih > DATE_SUB(NOW(), INTERVAL 1 WEEK) AND i.Ilan_Tarih <= NOW()";
            } else if (combobox_tarih.getSelectedItem() == "Son 1 Ay") {
                query += " AND i.Ilan_Tarih > DATE_SUB(NOW(), INTERVAL 1 MONTH) AND i.Ilan_Tarih <= NOW()";        
            }
        }
        if (!text_fiyatmin.getText().trim().isEmpty() && text_fiyatmax.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Fiyat >= '" + text_fiyatmin.getText() + "'";
        }
        if (text_fiyatmin.getText().trim().isEmpty() && !text_fiyatmax.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Fiyat <= '" + text_fiyatmax.getText() + "'";
        }
        if (!text_fiyatmin.getText().trim().isEmpty() && !text_fiyatmax.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Fiyat BETWEEN '" + text_fiyatmin.getText() + "' AND '" + text_fiyatmax.getText() + "'";
        }
        if (!text_kmmin.getText().trim().isEmpty() && text_kmmax.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Km >= '" + text_kmmin.getText() + "'";
        }
        if (text_kmmin.getText().trim().isEmpty() && !text_kmmax.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Km <= '" + text_kmmax.getText() + "'";
        }
        if (!text_kmmax.getText().trim().isEmpty() && !text_kmmin.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Km BETWEEN '" + text_kmmin.getText() + "' AND '" + text_kmmax.getText() + "'";
        }
        if (!text_ilanadi.getText().trim().isEmpty()) {
            query += " AND i.Ilan_Adi LIKE '%" + text_ilanadi.getText() + "%'";
        }
        if (checkbox_sehir1.isSelected()) {
            query += " ORDER BY s.Sehir ASC";
        }
        if (checkbox_sehir2.isSelected()) {
            query += " ORDER BY s.Sehir DESC";
        }
        if (checkbox_marka1.isSelected()) {
            query += " ORDER BY a.Araba_Marka ASC";
        }
        if (checkbox_marka2.isSelected()) {
            query += " ORDER BY a.Araba_Marka DESC";
        }
        if (checkbox_ilanadi1.isSelected()) {
            query += " ORDER BY i.Ilan_Adi ASC";
        }
        if (checkbox_ilanadi2.isSelected()) {
            query += " ORDER BY i.Ilan_Adi DESC";
        }
        if (checkbox_fiyat1.isSelected()) {
            query += " ORDER BY i.Ilan_Fiyat ASC";
        }
        if (checkbox_fiyat2.isSelected()) {
            query += " ORDER BY i.Ilan_Fiyat DESC";
        }
        if (checkbox_model1.isSelected()) {
            query += " ORDER BY a.Araba_Model ASC";
        }
        if (checkbox_model2.isSelected()) {
            query += " ORDER BY a.Araba_Model DESC";
        }
        if (checkbox_tarih1.isSelected()) {
            query += " ORDER BY i.Ilan_Tarih ASC";
        }
        if (checkbox_tarih2.isSelected()) {
            query += " ORDER BY i.Ilan_Tarih DESC";
        }
        if (checkbox_id1.isSelected()) {
            query += " ORDER BY i.IlanID ASC";
        }
        if (checkbox_id2.isSelected()) {
            query += " ORDER BY i.IlanID DESC";
        }
        if (checkbox_km1.isSelected()) {
            query += " ORDER BY i.Ilan_Km ASC";
        }
        if (checkbox_km2.isSelected()) {
            query += " ORDER BY i.Ilan_Km DESC";
        }
        ArrayList<SQL> rowlist = new ArrayList<SQL>();
        Statement st;
        ResultSet rs;
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            SQL records;
            while(rs.next()) {
                records = new SQL(rs.getInt("IlanID"), rs.getString("Ilan_Adi"), Float.parseFloat(rs.getString("Ilan_Fiyat")), Float.parseFloat(rs.getString("Ilan_Km")), rs.getString("Ilan_Tarih"), rs.getString("Araba_Marka"), rs.getString("Araba_Model"), rs.getString("Yakit_Turu"), rs.getString("Vites_Turu"), rs.getString("Renk"), rs.getString("Sehir"));
                rowlist.add(records);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FiltrelemeWindow.class.getName()).log(Level.SEVERE, null, ex);
        }   
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] kayit = new Object[11];
        for (int i=0; i < rowlist.size(); i++) {
            kayit[0] = rowlist.get(i).getId();
            kayit[1] = rowlist.get(i).getIlanadi();
            kayit[2] = rowlist.get(i).getFiyat();
            kayit[3] = rowlist.get(i).getKm();
            kayit[4] = rowlist.get(i).getTarih();
            kayit[5] = rowlist.get(i).getMarka();
            kayit[6] = rowlist.get(i).getModel();
            kayit[7] = rowlist.get(i).getYakitturu();
            kayit[8] = rowlist.get(i).getVitesturu();
            kayit[9] = rowlist.get(i).getRenk();
            kayit[10] = rowlist.get(i).getSehir();
            model.addRow(kayit);
        }
    }//GEN-LAST:event_Btn_SorgulaActionPerformed

    private void text_kmmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_kmmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_kmmaxActionPerformed

    private void checkbox_sehir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_sehir2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_sehir2ActionPerformed

    private void checkbox_fiyat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_fiyat2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_fiyat2ActionPerformed

    private void checkbox_marka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_marka2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_marka2ActionPerformed

    private void checkbox_model2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_model2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_model2ActionPerformed

    private void checkbox_ilanadi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_ilanadi2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_ilanadi2ActionPerformed

    private void checkbox_tarih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_tarih2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_tarih2ActionPerformed

    private void checkbox_sehir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_sehir1ActionPerformed
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_sehir1ActionPerformed

    private void checkbox_marka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_marka1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_marka1ActionPerformed

    private void checkbox_ilanadi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_ilanadi1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_ilanadi1ActionPerformed

    private void checkbox_fiyat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_fiyat1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_fiyat1ActionPerformed

    private void checkbox_model1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_model1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_model1ActionPerformed

    private void checkbox_tarih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_tarih1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_tarih1ActionPerformed

    private void checkbox_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_id1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_id1ActionPerformed

    private void checkbox_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_id2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_km1.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_id2ActionPerformed

    private void checkbox_km1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_km1ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km2.setSelected(false);
    }//GEN-LAST:event_checkbox_km1ActionPerformed

    private void checkbox_km2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_km2ActionPerformed
        checkbox_sehir1.setSelected(false);
        checkbox_sehir2.setSelected(false);
        checkbox_marka1.setSelected(false);
        checkbox_marka2.setSelected(false);
        checkbox_ilanadi1.setSelected(false);
        checkbox_ilanadi2.setSelected(false);
        checkbox_fiyat1.setSelected(false);
        checkbox_fiyat2.setSelected(false);
        checkbox_model1.setSelected(false);
        checkbox_model2.setSelected(false);
        checkbox_tarih1.setSelected(false);
        checkbox_tarih2.setSelected(false);
        checkbox_id1.setSelected(false);
        checkbox_id2.setSelected(false);
        checkbox_km1.setSelected(false);
    }//GEN-LAST:event_checkbox_km2ActionPerformed

    private void combobox_vitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_vitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_vitesActionPerformed

    private void combobox_yakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_yakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_yakitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_Sorgula;
    private javax.swing.JCheckBox checkbox_fiyat1;
    private javax.swing.JCheckBox checkbox_fiyat2;
    private javax.swing.JCheckBox checkbox_id1;
    private javax.swing.JCheckBox checkbox_id2;
    private javax.swing.JCheckBox checkbox_ilanadi1;
    private javax.swing.JCheckBox checkbox_ilanadi2;
    private javax.swing.JCheckBox checkbox_km1;
    private javax.swing.JCheckBox checkbox_km2;
    private javax.swing.JCheckBox checkbox_marka1;
    private javax.swing.JCheckBox checkbox_marka2;
    private javax.swing.JCheckBox checkbox_model1;
    private javax.swing.JCheckBox checkbox_model2;
    private javax.swing.JCheckBox checkbox_sehir1;
    private javax.swing.JCheckBox checkbox_sehir2;
    private javax.swing.JCheckBox checkbox_tarih1;
    private javax.swing.JCheckBox checkbox_tarih2;
    private javax.swing.JComboBox<String> combobox_renk;
    private javax.swing.JComboBox<String> combobox_sehir;
    private javax.swing.JComboBox<String> combobox_tarih;
    private javax.swing.JComboBox<String> combobox_vites;
    private javax.swing.JComboBox<String> combobox_yakit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_fiyat;
    private javax.swing.JLabel label_ilanadi;
    private javax.swing.JLabel label_km;
    private javax.swing.JLabel label_renk;
    private javax.swing.JLabel label_sehir;
    private javax.swing.JLabel label_sirala1;
    private javax.swing.JLabel label_sirala2;
    private javax.swing.JLabel label_sirala3;
    private javax.swing.JLabel label_sirala4;
    private javax.swing.JLabel label_sirala5;
    private javax.swing.JLabel label_sirala6;
    private javax.swing.JLabel label_sirala7;
    private javax.swing.JLabel label_sirala8;
    private javax.swing.JLabel label_tarih;
    private javax.swing.JLabel label_vites;
    private javax.swing.JLabel label_yakit;
    private javax.swing.JTextField text_fiyatmax;
    private javax.swing.JTextField text_fiyatmin;
    private javax.swing.JTextField text_ilanadi;
    private javax.swing.JTextField text_kmmax;
    private javax.swing.JTextField text_kmmin;
    // End of variables declaration//GEN-END:variables
}
