
package main;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Programlama Laboratuvari II Proje 4
 * @author Oguz Aktas
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_baslik = new javax.swing.JLabel();
        label_modul1 = new javax.swing.JLabel();
        label_modul2 = new javax.swing.JLabel();
        Btn_Ilan = new javax.swing.JButton();
        Btn_Araba = new javax.swing.JButton();
        Btn_YakitTuru = new javax.swing.JButton();
        Btn_Renk = new javax.swing.JButton();
        Btn_VitesTuru = new javax.swing.JButton();
        Btn_Sehir = new javax.swing.JButton();
        Btn_Filtreleme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        label_baslik.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_baslik.setForeground(new java.awt.Color(255, 51, 51));
        label_baslik.setText("Arac Alisveris Veritabani Programi");

        label_modul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_modul1.setText("1. Modul (Insert, Update, Delete)");

        label_modul2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_modul2.setText("2. Modul (Filtering)");

        Btn_Ilan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Ilan.setText("Tbl_Ilan");
        Btn_Ilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IlanActionPerformed(evt);
            }
        });

        Btn_Araba.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Araba.setText("Tbl_Araba");
        Btn_Araba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ArabaActionPerformed(evt);
            }
        });

        Btn_YakitTuru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_YakitTuru.setText("Tbl_YakitTuru");
        Btn_YakitTuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_YakitTuruActionPerformed(evt);
            }
        });

        Btn_Renk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Renk.setText("Tbl_Renk");
        Btn_Renk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RenkActionPerformed(evt);
            }
        });

        Btn_VitesTuru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_VitesTuru.setText("Tbl_VitesTuru");
        Btn_VitesTuru.setPreferredSize(new java.awt.Dimension(157, 45));
        Btn_VitesTuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VitesTuruActionPerformed(evt);
            }
        });

        Btn_Sehir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Sehir.setText("Tbl_Sehir");
        Btn_Sehir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SehirActionPerformed(evt);
            }
        });

        Btn_Filtreleme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Filtreleme.setText("Filtreleme");
        Btn_Filtreleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FiltrelemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Ilan)
                            .addComponent(Btn_YakitTuru)
                            .addComponent(Btn_VitesTuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Renk)
                            .addComponent(Btn_Sehir)
                            .addComponent(Btn_Araba)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(label_modul1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_modul2)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Filtreleme, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(label_baslik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label_baslik)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_modul1)
                    .addComponent(label_modul2))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Ilan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Filtreleme, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(Btn_Araba, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Btn_YakitTuru, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Btn_VitesTuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Btn_Renk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Btn_Sehir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_IlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IlanActionPerformed
        this.dispose();
        try {
            new IlanWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_IlanActionPerformed

    private void Btn_ArabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ArabaActionPerformed
        this.dispose();
        try {
            new ArabaWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_ArabaActionPerformed

    private void Btn_YakitTuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_YakitTuruActionPerformed
        this.dispose();
        try {
            new YakitTuruWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_YakitTuruActionPerformed

    private void Btn_RenkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RenkActionPerformed
        this.dispose();
        try {
            new RenkWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_RenkActionPerformed

    private void Btn_VitesTuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VitesTuruActionPerformed
        this.dispose();
        try {
            new VitesTuruWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_VitesTuruActionPerformed

    private void Btn_SehirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SehirActionPerformed
        this.dispose();
        try {
            new SehirWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_SehirActionPerformed

    private void Btn_FiltrelemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FiltrelemeActionPerformed
        this.dispose();
        try {
            new FiltrelemeWindow().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_FiltrelemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Araba;
    private javax.swing.JButton Btn_Filtreleme;
    private javax.swing.JButton Btn_Ilan;
    private javax.swing.JButton Btn_Renk;
    private javax.swing.JButton Btn_Sehir;
    private javax.swing.JButton Btn_VitesTuru;
    private javax.swing.JButton Btn_YakitTuru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_baslik;
    private javax.swing.JLabel label_modul1;
    private javax.swing.JLabel label_modul2;
    // End of variables declaration//GEN-END:variables
}
