
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Programlama Laboratuvari II Proje 4
 * @author Oguz Aktas
 */
public class YakitTuruWindow extends javax.swing.JFrame {

    /**
     * Creates new form YakitTuruWindow
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public YakitTuruWindow() throws SQLException, ClassNotFoundException {
        initComponents();
        yakitturlerinitablodaGoster();
    }
    
    public Connection getConnection() throws SQLException, ClassNotFoundException {
        Connection conn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/arac_alisveris", "root", "123456");
            return conn;
        } catch (SQLException ex) {
            Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Veritabanina baglanti saglanamadi");
        }
        return null;
    }
    
    public boolean checkInputs() {
        if (text_yakitturu.getText().trim().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }
    
    public ArrayList<YakitTuru> getYakitTuruList() throws SQLException, ClassNotFoundException {
        ArrayList<YakitTuru> yakitturulistesi = new ArrayList<YakitTuru>();
        Connection conn = getConnection();
        String query = "SELECT * FROM Tbl_YakitTuru;";
        Statement st;
        ResultSet rs;
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            YakitTuru yakitturu;
            while(rs.next()) {
                yakitturu = new YakitTuru(rs.getInt("YakitTuruID"), rs.getString("Yakit_Turu"));
                yakitturulistesi.add(yakitturu);
            }
        } catch (SQLException ex) {
            Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return yakitturulistesi;
    }
    
    public void yakitturlerinitablodaGoster() throws SQLException, ClassNotFoundException {
        ArrayList<YakitTuru> list = getYakitTuruList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] kayit = new Object[2];
        for (int i=0; i < list.size(); i++) {
            kayit[0] = list.get(i).getId();
            kayit[1] = list.get(i).getYakitturu();
            model.addRow(kayit);
        }
    }
    
    public void showItem(int index) throws SQLException, ClassNotFoundException {
        text_id.setText(Integer.toString(getYakitTuruList().get(index).getId()));
        text_yakitturu.setText(getYakitTuruList().get(index).getYakitturu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        label_yakitturu = new javax.swing.JLabel();
        text_yakitturu = new javax.swing.JTextField();
        text_id = new javax.swing.JTextField();
        Btn_Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Btn_Insert = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        Btn_Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        label_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_id.setText("Yakit Turu ID : ");

        label_yakitturu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_yakitturu.setText("Yakit Turu : ");

        text_yakitturu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_yakitturu.setPreferredSize(new java.awt.Dimension(69, 39));
        text_yakitturu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_yakitturuActionPerformed(evt);
            }
        });

        text_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_id.setPreferredSize(new java.awt.Dimension(69, 39));
        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });

        Btn_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/update.png"))); // NOI18N
        Btn_Update.setText("Update");
        Btn_Update.setIconTextGap(10);
        Btn_Update.setPreferredSize(new java.awt.Dimension(131, 51));
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Yakit Turu ID", "Yakit Turu"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Btn_Insert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/add.png"))); // NOI18N
        Btn_Insert.setText("Insert");
        Btn_Insert.setIconTextGap(10);
        Btn_Insert.setPreferredSize(new java.awt.Dimension(180, 51));
        Btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InsertActionPerformed(evt);
            }
        });

        Btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/delete.png"))); // NOI18N
        Btn_Delete.setText("Delete");
        Btn_Delete.setIconTextGap(10);
        Btn_Delete.setPreferredSize(new java.awt.Dimension(131, 51));
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        Btn_Menu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/home.png"))); // NOI18N
        Btn_Menu.setText("Ana Ekrana Git");
        Btn_Menu.setIconTextGap(10);
        Btn_Menu.setPreferredSize(new java.awt.Dimension(180, 51));
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_yakitturu)
                            .addComponent(label_id))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_yakitturu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_id)
                            .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_yakitturu)
                            .addComponent(text_yakitturu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_yakitturuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_yakitturuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_yakitturuActionPerformed

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
        if (checkInputs() && text_id.getText() != null) {
            String query = null;
            Connection conn = null;
            try {
                conn = getConnection();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps = null;
            query = "UPDATE Tbl_YakitTuru SET Yakit_Turu = ? WHERE YakitTuruID = ?;";
            try {
                ps = conn.prepareStatement(query);
                ps.setString(1, text_yakitturu.getText());
                ps.setInt(2, Integer.parseInt(text_id.getText()));
                ps.executeUpdate();
                yakitturlerinitablodaGoster();
                JOptionPane.showMessageDialog(null, "Kayit guncellendi.");
            } catch (SQLException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Kayit guncelleme sirasinda hata olustu.");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bir ya da daha fazla alani bos biraktiniz.");
        }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        try {
            showItem(index);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void Btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InsertActionPerformed
        if (checkInputs()) {
            Connection conn = null;
            try {
                conn = getConnection();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps;
            try {
                if (text_id.getText().trim().isEmpty()) {
                    ps = conn.prepareStatement("INSERT INTO Tbl_YakitTuru(Yakit_Turu) VALUES(?);");
                    ps.setString(1, text_yakitturu.getText());
                } else {
                    ps = conn.prepareStatement("INSERT INTO Tbl_YakitTuru(YakitTuruID, Yakit_Turu) VALUES(?, ?);");
                    ps.setString(1, text_id.getText());
                    ps.setString(2, text_yakitturu.getText());
                }
                ps.executeUpdate();
                yakitturlerinitablodaGoster();
                JOptionPane.showMessageDialog(null, "Kayit eklendi.");
            } catch (SQLException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Kayit ekleme sirasinda hata olustu.");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bir ya da daha fazla alani bos biraktiniz.");
        }
    }//GEN-LAST:event_Btn_InsertActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        if(!text_id.getText().equals("")) {
            Connection conn = null;
            try {
                conn = getConnection();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement ps = conn.prepareStatement("DELETE FROM Tbl_YakitTuru WHERE YakitTuruID = ?;");
                int id = Integer.parseInt(text_id.getText());
                ps.setInt(1, id);
                ps.executeUpdate();
                yakitturlerinitablodaGoster();
                JOptionPane.showMessageDialog(null, "Kayit silindi.");
            } catch (SQLException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Kayit silinme sirasinda hata olustu.");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(YakitTuruWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kayit silinemedi. Dogru ID numarasini girdiginizden emin olun.");
        }
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        this.dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_Btn_MenuActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_Insert;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_yakitturu;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_yakitturu;
    // End of variables declaration//GEN-END:variables
}
